# ===============================
# DATASOURCE (LOCAL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/iugo?options=-c%20TimeZone%3DUTC
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SECURITY / JWT
# ===============================
security.jwt.secret=aUjC5LbT6PA8e4JADq0DIGtS3isEj6GwqIqPwhkvlFU=
security.jwt.expiration-minutes=60

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.com.iugo.demo=DEBUG

# ===============================
# SEED
# ===============================
app.seed.enabled=true