# ===============================
# DATASOURCE (PROD)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SECURITY / JWT
# ===============================
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-minutes=60

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=INFO
logging.level.com.iugo.demo=INFO

# ===============================
# SEED
# ===============================
app.seed.enabled=false